### ISSUE TITLE
Subclassing `Help` in a JavaScript project throws errors

### ISSUE THREAD

**Issue by tarkatronic** [oclif/plugin-help#67]
Steps to reproduce:

1. Create a new JavaScript project
    ```sh
    $ npx oclif multi test-command
    ```
1. Create `test-command/src/help.js`
   ```js
    const { Help } = require('@oclif/plugin-help');
    
    module.exports = class TestHelp extends Help {
      showHelp(args) {
        console.log('Hello, world! I am customized help!');
        super.showHelp(args);
      }
    };
    ```
1. Add `oclif.helpClass` key to `package.json`:
    ```json
    {
      "oclif": {
        "helpClass": "./src/help"
      }
    }
    ```
1. Run command:
    ```sh
    $ node bin/run
    Error: Unable to load configured help class "./src/help", failed with message:
    Class extends value undefined is not a constructor or null
        at Object.getHelpClass (~/workspace/test-command/node_modules/@oclif/plugin-help/lib/util.js:66:19)
        at Main._help (~/workspace/test-command/node_modules/@oclif/command/lib/main.js:40:41)
        at Main.init (~/workspace/test-command/node_modules/@oclif/command/lib/command.js:81:25)
        at Main.init (~/workspace/test-command/node_modules/@oclif/command/lib/main.js:12:22)
        at async Main._run (~/workspace/test-command/node_modules/@oclif/command/lib/command.js:42:13)
    ```

[The documentation](https://oclif.io/docs/help_classes#building-custom-help-classes-in-javascript-projects) currently only shows extending `HelpBase` in JavaScript projects, although the second example appears to be showing an example which would be extending `Help`. If I change my example to extend `HelpBase`, it fails in a different yet predictable fashion:

```sh
$ node bin/run
Hello, world! I am customized help!
TypeError: (intermediate value).showHelp is not a function
    at TestHelp.showHelp (~/workspace/test-command/src/help.js:6:11)
    at Main._help (~/workspace/test-command/node_modules/@oclif/command/lib/main.js:42:14)
    at Main.init (~/workspace/test-command/node_modules/@oclif/command/lib/command.js:81:25)
    at Main.init (~/workspace/test-command/node_modules/@oclif/command/lib/main.js:12:22)
    at async Main._run (~/workspace/test-command/node_modules/@oclif/command/lib/command.js:42:13)
```

**Comment by childish-sambino** [comment]
Think this is similar to https://github.com/oclif/plugin-plugins/issues/97. Temporary fix/hack is to pin tslib to `1.11.2`.

**Comment by tarkatronic** [comment]
@childish-sambino Sadly, that had no effect. I still get the same errors, even with `tslib` pinned.

**Comment by RasPhilCo** [comment]
Thanks for bringing this to our attention!
